### ISSUE TITLE
get_oracle_db_id - oracle_id Reset When Multiple DBs in Loop

### ISSUE THREAD

**Issue by gray-al** [pcrouleur/rubrik_oracle_tools#3]
https://github.com/pcrouleur/rubrik_oracle_tools/blob/90445d027089ffde140f36c1c352b68527c5fe85/rbs_oracle_common.py#L123

In the get_oracle_db_id method, we have the situation where we can't get an oracle_id value returned.  This happened after we migrated a database to a new host.  For the duration of our SLA retention policy we'll have snapshots registered with old and new IDs.  In the rubrik API this means we have 2 IDs for this database name and different `standaloneHostName` values.  

At line 118, we'll loop over these 2 db's data sets.  The first pass will set oracle_id correctly because our supplied database_host value and standaloneHostName match.  On the 2nd pass of the for loop, the database_host != standaloneHostName check happens and we set oracle_id back to None, overwriting our previous correct ID.  

Would it make sense to remove the `oracle_id = None` at line 123 and just break?   oracle_id is already initialized to None at line 113 so if we have no matches, we still hit the `No ID found...` check.  and probably the same removal needed at line 134.

Example call:
```
 rbs_oracle_common.RubrikRbsOracleDatabase(rubrik, database_host="new_host", database_name="db1")
```
Example api data (oracle_dbs):
```
{
  "hasMore": "false",
  "data": [
    {
      "id": "OracleDatabase:::d1234cc1-4544-410b-c3p0-5467345644",
      "name": "db1",
       ...
      "standaloneHostName": "new_host"
    },
    {
      "id": "OracleDatabase:::d12341e8-4454-4450-r2d2-423452345d",
      "name": "db1",
       ...
      "standaloneHostName": "old_host"
    }
  ],
  "total": 2
}
```

**Comment by pcrouleur** [comment]
Good catch. That is a bug. I'm thinking of moving the host name check into a function, so I can eliminate the inner loop and instead break when the hostname is a match.  Working on that now. Thanks!

**Comment by pcrouleur** [comment]
I have a fix to test in a new branch - db_id_fix. I'm testing now and so far so good. If you can switch to that branch and let me know if this fixes your issue, I would appreciate it. It's hard to test all these permutations. Thanks!

**Comment by pcrouleur** [comment]
The fix seems to be working, so I merged it into the master.  I am deleting the db_id_fix branch. Let me know if this resolves your issue. Thanks!

**Comment by gray-al** [comment]
Thanks for the quick fix!  We did make the same fix locally to get unblocked and it did fix our issue.

**Comment by gray-al** [comment]
I just saw your commit included the host name function too - we'll work on getting that pulled in and verify it but it looks pretty straight forward.
