### ISSUE TITLE
rubrik_oracle_backup_clone always restores spfile even if no_spfile=true

### ISSUE THREAD

**Issue by gilesem** [pcrouleur/rubrik_oracle_tools#4]
When running rubrik_oracle_backup_clone.py I noticed the RMAN duplicate command always restored the spfile from backup even when no_spfile=true was specified in the parameter file.  

Suggesting [line 106](https://github.com/pcrouleur/rubrik_oracle_tools/blob/master/rubrik_oracle_backup_clone.py#L106) be updated from 
`no_spfile = configuration['parameters'].getboolean('spfile')`
to
`no_spfile = configuration['parameters'].getboolean('no_spfile')`

**Comment by pcrouleur** [comment]
Thanks for catching that. Definitely a typo. Your fix is in place and pushed to the master.

**Comment by gilesem** [comment]
Thanks for the quick response.
